name: CI
on: [push]

jobs:
    CI:
        name: CI
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup mise
              uses: jdx/mise-action@v2
              with:
                  install: true
                  cache: true

            - name: StyLua Check
              run: stylua --check .
